### ISSUE TITLE
Blockchair

### ISSUE THREAD

**Issue by Dustone25** [nlitsme/python-bcutils#1]
Blokchain | Group | API path prefix | Support status
-- | -- | -- | --
Bitcoin | Bitcoin-like | https://api.blockchair.com/bitcoin | Full support
Bitcoin Cash | Bitcoin-like | https://api.blockchair.com/bitcoin-cash | Full support
Ethereum | Ethereum-like | https://api.blockchair.com/ethereum | Full support
Litecoin | Bitcoin-like | https://api.blockchair.com/litecoin | Full support
Bitcoin SV | Bitcoin-like | https://api.blockchair.com/bitcoin-sv | Full support
Dogecoin | Bitcoin-like | https://api.blockchair.com/dogecoin | Full support
Dash | Bitcoin-like | https://api.blockchair.com/dash | Full support
Ripple | Ripple-like | https://api.blockchair.com/ripple | Alpha mode, possible compatibility-breaking changes
Groestlcoin | Bitcoin-like | https://api.blockchair.com/groestlcoin | Full support at least till January 1st, 2021
Stellar | Stellar-like | https://api.blockchair.com/stellar | Alpha mode, possible compatibility-breaking changes
Monero | Monero-like | https://api.blockchair.com/monero | Alpha mode, possible compatibility-breaking changes
Cardano | Cardano-like | https://api.blockchair.com/cardano | Alpha mode, possible compatibility-breaking changes
Zcash | Bitcoin-like | https://api.blockchair.com/zcash | Full support
Mixin | Mixin-like | https://api.blockchair.com/mixin | Full support at least till April 24th, 2021
Tezos | Tezos-like | https://api.blockchair.com/tezos | Alpha mode, possible compatibility-breaking changes
EOS | EOS-like | https://api.blockchair.com/eos | Alpha mode, possible compatibility-breaking changes
eCash | Bitcoin-like | https://api.blockchair.com/ecash | Beta mode, possible instability. Also known as Bitcoin Cash ABC and Bitcoin ABC.

<p style="-webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; border: none; box-shadow: none; box-sizing: border-box; outline: none; text-decoration: none; text-indent: 0px; margin: 1em 0px; padding: 0px; margin-block: 0px; margin-inline: 0px; color: rgb(10, 10, 10); font-family: Inter, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 242, 249);">Please note there are some endpoints which aren't listed here (most of the times they have the<span> </span><code style="-webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; border: 1px solid rgba(33, 112, 255, 0.15); box-shadow: none; box-sizing: border-box; outline: none; text-decoration: none; text-indent: 0px; margin: 0px; padding: 3px 8px 4px; color: var(--c-red-d1); font-family: &quot;DM Mono&quot;, monospace; word-break: break-all; background-color: var(--c-bg-plain-d1); border-radius: 5px;">https://api.blockchair.com/internal</code><span> </span>prefix), but used by our web interface — these endpoints aren't meant to be used by 3rd parties.</p><p style="-webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; border: none; box-shadow: none; box-sizing: border-box; outline: none; text-decoration: none; text-indent: 0px; margin: 1em 0px; padding: 0px; margin-block: 0px; margin-inline: 0px; color: rgb(10, 10, 10); font-family: Inter, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(239, 242, 249);">The base request cost is used only if there are no additional parameters included in the request, and the default limits on the number of results are used. For example, if you're requesting info on ERC-20 tokens while getting data on an Ethereum address using a special parameter or increasing the number of latest transactions for this address, you may be charged additional request points.<span> </span><code style="-webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; border: 1px solid rgba(33, 112, 255, 0.15); box-shadow: none; box-sizing: border-box; outline: none; text-decoration: none; text-indent: 0px; margin: 0px; padding: 3px 8px 4px; color: var(--c-red-d1); font-family: &quot;DM Mono&quot;, monospace; word-break: break-all; background-color: var(--c-bg-plain-d1); border-radius: 5px;">c</code><span> </span>in formulas means "number of requested entities".<span> </span><code style="-webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; border: 1px solid rgba(33, 112, 255, 0.15); box-shadow: none; box-sizing: border-box; outline: none; text-decoration: none; text-indent: 0px; margin: 0px; padding: 3px 8px 4px; color: var(--c-red-d1); font-family: &quot;DM Mono&quot;, monospace; word-break: break-all; background-color: var(--c-bg-plain-d1); border-radius: 5px;">d</code><span> </span>means "depth" (applied to xpub lookups). Detailed cost formulas are available in the corresponding documentation sections.</p>

**Comment by nlitsme** [comment]
I am not sure what your question is.

**Comment by Dustone25** [comment]
I need help are able to help me do some clone type of dev and teach me how
to do my blockchair well I'm trying to figure this out just barely started
and was wanting to build the blockchair with the wallet added on to it??
